#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package com::ibm::streamsx::thrift::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


1;
