#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use Thrift;

use com::ibm::streamsx::thrift::Types;

# HELPER FUNCTIONS AND STRUCTURES

package com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_args;
use base qw(Class::Accessor);
com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_args->mk_accessors( qw( request ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{request} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{request}) {
      $self->{request} = $vals->{request};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'ThriftSource_1_sendSync_0_args';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == TType::BOOL) {
        $xfer += $input->readBool(\$self->{request});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('ThriftSource_1_sendSync_0_args');
  if (defined $self->{request}) {
    $xfer += $output->writeFieldBegin('request', TType::BOOL, 1);
    $xfer += $output->writeBool($self->{request});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_result;
use base qw(Class::Accessor);
com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_result->mk_accessors( qw( success ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{success} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{success}) {
      $self->{success} = $vals->{success};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'ThriftSource_1_sendSync_0_result';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^0$/ && do{      if ($ftype == TType::STRUCT) {
        $self->{success} = new com::ibm::streamsx::thrift::SendResponse_0();
        $xfer += $self->{success}->read($input);
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('ThriftSource_1_sendSync_0_result');
  if (defined $self->{success}) {
    $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
    $xfer += $self->{success}->write($output);
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package com::ibm::streamsx::thrift::ThriftSource_1_sendAsync_0_args;
use base qw(Class::Accessor);
com::ibm::streamsx::thrift::ThriftSource_1_sendAsync_0_args->mk_accessors( qw( request ) );

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  $self->{request} = undef;
  if (UNIVERSAL::isa($vals,'HASH')) {
    if (defined $vals->{request}) {
      $self->{request} = $vals->{request};
    }
  }
  return bless ($self, $classname);
}

sub getName {
  return 'ThriftSource_1_sendAsync_0_args';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
      /^1$/ && do{      if ($ftype == TType::BOOL) {
        $xfer += $input->readBool(\$self->{request});
      } else {
        $xfer += $input->skip($ftype);
      }
      last; };
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('ThriftSource_1_sendAsync_0_args');
  if (defined $self->{request}) {
    $xfer += $output->writeFieldBegin('request', TType::BOOL, 1);
    $xfer += $output->writeBool($self->{request});
    $xfer += $output->writeFieldEnd();
  }
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package com::ibm::streamsx::thrift::ThriftSource_1_sendAsync_0_result;
use base qw(Class::Accessor);

sub new {
  my $classname = shift;
  my $self      = {};
  my $vals      = shift || {};
  return bless ($self, $classname);
}

sub getName {
  return 'ThriftSource_1_sendAsync_0_result';
}

sub read {
  my ($self, $input) = @_;
  my $xfer  = 0;
  my $fname;
  my $ftype = 0;
  my $fid   = 0;
  $xfer += $input->readStructBegin(\$fname);
  while (1) 
  {
    $xfer += $input->readFieldBegin(\$fname, \$ftype, \$fid);
    if ($ftype == TType::STOP) {
      last;
    }
    SWITCH: for($fid)
    {
        $xfer += $input->skip($ftype);
    }
    $xfer += $input->readFieldEnd();
  }
  $xfer += $input->readStructEnd();
  return $xfer;
}

sub write {
  my ($self, $output) = @_;
  my $xfer   = 0;
  $xfer += $output->writeStructBegin('ThriftSource_1_sendAsync_0_result');
  $xfer += $output->writeFieldStop();
  $xfer += $output->writeStructEnd();
  return $xfer;
}

package com::ibm::streamsx::thrift::ThriftSource_1If;

use strict;


sub sendSync_0{
  my $self = shift;
  my $request = shift;

  die 'implement interface';
}

sub sendAsync_0{
  my $self = shift;
  my $request = shift;

  die 'implement interface';
}

package com::ibm::streamsx::thrift::ThriftSource_1Rest;

use strict;


sub new {
  my ($classname, $impl) = @_;
  my $self     ={ impl => $impl };

  return bless($self,$classname);
}

sub sendSync_0{
  my ($self, $request) = @_;

  my $request = ($request->{'request'}) ? $request->{'request'} : undef;
  return $self->{impl}->sendSync_0($request);
}

sub sendAsync_0{
  my ($self, $request) = @_;

  my $request = ($request->{'request'}) ? $request->{'request'} : undef;
  return $self->{impl}->sendAsync_0($request);
}

package com::ibm::streamsx::thrift::ThriftSource_1Client;


use base qw(com::ibm::streamsx::thrift::ThriftSource_1If);
sub new {
  my ($classname, $input, $output) = @_;
  my $self      = {};
  $self->{input}  = $input;
  $self->{output} = defined $output ? $output : $input;
  $self->{seqid}  = 0;
  return bless($self,$classname);
}

sub sendSync_0{
  my $self = shift;
  my $request = shift;

    $self->send_sendSync_0($request);
  return $self->recv_sendSync_0();
}

sub send_sendSync_0{
  my $self = shift;
  my $request = shift;

  $self->{output}->writeMessageBegin('sendSync_0', TMessageType::CALL, $self->{seqid});
  my $args = new com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_args();
  $args->{request} = $request;
  $args->write($self->{output});
  $self->{output}->writeMessageEnd();
  $self->{output}->getTransport()->flush();
}

sub recv_sendSync_0{
  my $self = shift;

  my $rseqid = 0;
  my $fname;
  my $mtype = 0;

  $self->{input}->readMessageBegin(\$fname, \$mtype, \$rseqid);
  if ($mtype == TMessageType::EXCEPTION) {
    my $x = new TApplicationException();
    $x->read($self->{input});
    $self->{input}->readMessageEnd();
    die $x;
  }
  my $result = new com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_result();
  $result->read($self->{input});
  $self->{input}->readMessageEnd();

  if (defined $result->{success} ) {
    return $result->{success};
  }
  die "sendSync_0 failed: unknown result";
}
sub sendAsync_0{
  my $self = shift;
  my $request = shift;

    $self->send_sendAsync_0($request);
}

sub send_sendAsync_0{
  my $self = shift;
  my $request = shift;

  $self->{output}->writeMessageBegin('sendAsync_0', TMessageType::CALL, $self->{seqid});
  my $args = new com::ibm::streamsx::thrift::ThriftSource_1_sendAsync_0_args();
  $args->{request} = $request;
  $args->write($self->{output});
  $self->{output}->writeMessageEnd();
  $self->{output}->getTransport()->flush();
}
package com::ibm::streamsx::thrift::ThriftSource_1Processor;

use strict;


sub new {
    my ($classname, $handler) = @_;
    my $self      = {};
    $self->{handler} = $handler;
    return bless ($self, $classname);
}

sub process {
    my ($self, $input, $output) = @_;
    my $rseqid = 0;
    my $fname  = undef;
    my $mtype  = 0;

    $input->readMessageBegin(\$fname, \$mtype, \$rseqid);
    my $methodname = 'process_'.$fname;
    if (!$self->can($methodname)) {
      $input->skip(TType::STRUCT);
      $input->readMessageEnd();
      my $x = new TApplicationException('Function '.$fname.' not implemented.', TApplicationException::UNKNOWN_METHOD);
      $output->writeMessageBegin($fname, TMessageType::EXCEPTION, $rseqid);
      $x->write($output);
      $output->writeMessageEnd();
      $output->getTransport()->flush();
      return;
    }
    $self->$methodname($rseqid, $input, $output);
    return 1;
}

sub process_sendSync_0 {
    my ($self, $seqid, $input, $output) = @_;
    my $args = new com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_args();
    $args->read($input);
    $input->readMessageEnd();
    my $result = new com::ibm::streamsx::thrift::ThriftSource_1_sendSync_0_result();
    $result->{success} = $self->{handler}->sendSync_0($args->request);
    $output->writeMessageBegin('sendSync_0', TMessageType::REPLY, $seqid);
    $result->write($output);
    $output->writeMessageEnd();
    $output->getTransport()->flush();
}

sub process_sendAsync_0 {
    my ($self, $seqid, $input, $output) = @_;
    my $args = new com::ibm::streamsx::thrift::ThriftSource_1_sendAsync_0_args();
    $args->read($input);
    $input->readMessageEnd();
    $self->{handler}->sendAsync_0($args->request);
    return;
}
1;
