/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace com.ibm.streamsx.thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SendResponse_0 : TBase
  {

    public Dictionary<int, string> Result { get; set; }

    public SendResponse_0() {
    }

    public SendResponse_0(Dictionary<int, string> result) : this() {
      this.Result = result;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_result = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                Result = new Dictionary<int, string>();
                TMap _map0 = iprot.ReadMapBegin();
                for( int _i1 = 0; _i1 < _map0.Count; ++_i1)
                {
                  int _key2;
                  string _val3;
                  _key2 = iprot.ReadI32();
                  _val3 = iprot.ReadString();
                  Result[_key2] = _val3;
                }
                iprot.ReadMapEnd();
              }
              isset_result = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_result)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SendResponse_0");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "result";
      field.Type = TType.Map;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.I32, TType.String, Result.Count));
        foreach (int _iter4 in Result.Keys)
        {
          oprot.WriteI32(_iter4);
          oprot.WriteString(Result[_iter4]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SendResponse_0(");
      sb.Append("Result: ");
      sb.Append(Result);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
