/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace com.ibm.streamsx.thrift
{
  public partial class ThriftSource_1 {
    public interface Iface {
      SendResponse_0 sendSync_0(bool request);
      #if SILVERLIGHT
      IAsyncResult Begin_sendSync_0(AsyncCallback callback, object state, bool request);
      SendResponse_0 End_sendSync_0(IAsyncResult asyncResult);
      #endif
      void sendAsync_0(bool request);
      #if SILVERLIGHT
      IAsyncResult Begin_sendAsync_0(AsyncCallback callback, object state, bool request);
      void End_sendAsync_0(IAsyncResult asyncResult);
      #endif
    }

    public class Client : IDisposable, Iface {
      public Client(TProtocol prot) : this(prot, prot)
      {
      }

      public Client(TProtocol iprot, TProtocol oprot)
      {
        iprot_ = iprot;
        oprot_ = oprot;
      }

      protected TProtocol iprot_;
      protected TProtocol oprot_;
      protected int seqid_;

      public TProtocol InputProtocol
      {
        get { return iprot_; }
      }
      public TProtocol OutputProtocol
      {
        get { return oprot_; }
      }


      #region " IDisposable Support "
      private bool _IsDisposed;

      // IDisposable
      public void Dispose()
      {
        Dispose(true);
      }
      

      protected virtual void Dispose(bool disposing)
      {
        if (!_IsDisposed)
        {
          if (disposing)
          {
            if (iprot_ != null)
            {
              ((IDisposable)iprot_).Dispose();
            }
            if (oprot_ != null)
            {
              ((IDisposable)oprot_).Dispose();
            }
          }
        }
        _IsDisposed = true;
      }
      #endregion


      
      #if SILVERLIGHT
      public IAsyncResult Begin_sendSync_0(AsyncCallback callback, object state, bool request)
      {
        return send_sendSync_0(callback, state, request);
      }

      public SendResponse_0 End_sendSync_0(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
        return recv_sendSync_0();
      }

      #endif

      public SendResponse_0 sendSync_0(bool request)
      {
        #if !SILVERLIGHT
        send_sendSync_0(request);
        return recv_sendSync_0();

        #else
        var asyncResult = Begin_sendSync_0(null, null, request);
        return End_sendSync_0(asyncResult);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_sendSync_0(AsyncCallback callback, object state, bool request)
      #else
      public void send_sendSync_0(bool request)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("sendSync_0", TMessageType.Call, seqid_));
        sendSync_0_args args = new sendSync_0_args();
        args.Request = request;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

      public SendResponse_0 recv_sendSync_0()
      {
        TMessage msg = iprot_.ReadMessageBegin();
        if (msg.Type == TMessageType.Exception) {
          TApplicationException x = TApplicationException.Read(iprot_);
          iprot_.ReadMessageEnd();
          throw x;
        }
        sendSync_0_result result = new sendSync_0_result();
        result.Read(iprot_);
        iprot_.ReadMessageEnd();
        if (result.__isset.success) {
          return result.Success;
        }
        throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "sendSync_0 failed: unknown result");
      }

      
      #if SILVERLIGHT
      public IAsyncResult Begin_sendAsync_0(AsyncCallback callback, object state, bool request)
      {
        return send_sendAsync_0(callback, state, request);
      }

      public void End_sendAsync_0(IAsyncResult asyncResult)
      {
        oprot_.Transport.EndFlush(asyncResult);
      }

      #endif

      public void sendAsync_0(bool request)
      {
        #if !SILVERLIGHT
        send_sendAsync_0(request);

        #else
        var asyncResult = Begin_sendAsync_0(null, null, request);

        #endif
      }
      #if SILVERLIGHT
      public IAsyncResult send_sendAsync_0(AsyncCallback callback, object state, bool request)
      #else
      public void send_sendAsync_0(bool request)
      #endif
      {
        oprot_.WriteMessageBegin(new TMessage("sendAsync_0", TMessageType.Call, seqid_));
        sendAsync_0_args args = new sendAsync_0_args();
        args.Request = request;
        args.Write(oprot_);
        oprot_.WriteMessageEnd();
        #if SILVERLIGHT
        return oprot_.Transport.BeginFlush(callback, state);
        #else
        oprot_.Transport.Flush();
        #endif
      }

    }
    public class Processor : TProcessor {
      public Processor(Iface iface)
      {
        iface_ = iface;
        processMap_["sendSync_0"] = sendSync_0_Process;
        processMap_["sendAsync_0"] = sendAsync_0_Process;
      }

      protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
      private Iface iface_;
      protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

      public bool Process(TProtocol iprot, TProtocol oprot)
      {
        try
        {
          TMessage msg = iprot.ReadMessageBegin();
          ProcessFunction fn;
          processMap_.TryGetValue(msg.Name, out fn);
          if (fn == null) {
            TProtocolUtil.Skip(iprot, TType.Struct);
            iprot.ReadMessageEnd();
            TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
            oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
            x.Write(oprot);
            oprot.WriteMessageEnd();
            oprot.Transport.Flush();
            return true;
          }
          fn(msg.SeqID, iprot, oprot);
        }
        catch (IOException)
        {
          return false;
        }
        return true;
      }

      public void sendSync_0_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        sendSync_0_args args = new sendSync_0_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        sendSync_0_result result = new sendSync_0_result();
        result.Success = iface_.sendSync_0(args.Request);
        oprot.WriteMessageBegin(new TMessage("sendSync_0", TMessageType.Reply, seqid)); 
        result.Write(oprot);
        oprot.WriteMessageEnd();
        oprot.Transport.Flush();
      }

      public void sendAsync_0_Process(int seqid, TProtocol iprot, TProtocol oprot)
      {
        sendAsync_0_args args = new sendAsync_0_args();
        args.Read(iprot);
        iprot.ReadMessageEnd();
        iface_.sendAsync_0(args.Request);
        return;
      }
    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class sendSync_0_args : TBase
    {
      private bool _request;

      public bool Request
      {
        get
        {
          return _request;
        }
        set
        {
          __isset.request = true;
          this._request = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool request;
      }

      public sendSync_0_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                Request = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("sendSync_0_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.request) {
          field.Name = "request";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Request);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("sendSync_0_args(");
        sb.Append("Request: ");
        sb.Append(Request);
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class sendSync_0_result : TBase
    {
      private SendResponse_0 _success;

      public SendResponse_0 Success
      {
        get
        {
          return _success;
        }
        set
        {
          __isset.success = true;
          this._success = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool success;
      }

      public sendSync_0_result() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.Struct) {
                Success = new SendResponse_0();
                Success.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("sendSync_0_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.Struct;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            Success.Write(oprot);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("sendSync_0_result(");
        sb.Append("Success: ");
        sb.Append(Success== null ? "<null>" : Success.ToString());
        sb.Append(")");
        return sb.ToString();
      }

    }


    #if !SILVERLIGHT
    [Serializable]
    #endif
    public partial class sendAsync_0_args : TBase
    {
      private bool _request;

      public bool Request
      {
        get
        {
          return _request;
        }
        set
        {
          __isset.request = true;
          this._request = value;
        }
      }


      public Isset __isset;
      #if !SILVERLIGHT
      [Serializable]
      #endif
      public struct Isset {
        public bool request;
      }

      public sendAsync_0_args() {
      }

      public void Read (TProtocol iprot)
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                Request = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }

      public void Write(TProtocol oprot) {
        TStruct struc = new TStruct("sendAsync_0_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.request) {
          field.Name = "request";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(Request);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }

      public override string ToString() {
        StringBuilder sb = new StringBuilder("sendAsync_0_args(");
        sb.Append("Request: ");
        sb.Append(Request);
        sb.Append(")");
        return sb.ToString();
      }

    }

  }
}
