// Copyright (C) 2005 Arkadiy Vertleyb
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.streams_boost.org/LICENSE_1_0.txt)

#ifndef STREAMS_BOOST_TYPEOF_INTEGRAL_TEMPLATE_PARAM_HPP_INCLUDED
#define STREAMS_BOOST_TYPEOF_INTEGRAL_TEMPLATE_PARAM_HPP_INCLUDED

#define STREAMS_BOOST_TYPEOF_unsigned (unsigned)
#define STREAMS_BOOST_TYPEOF_signed (signed)

#define char_STREAMS_BOOST_TYPEOF (char)
#define short_STREAMS_BOOST_TYPEOF (short)
#define int_STREAMS_BOOST_TYPEOF (int)
#define long_STREAMS_BOOST_TYPEOF (long)

#define STREAMS_BOOST_TYPEOF_char_STREAMS_BOOST_TYPEOF (char)
#define STREAMS_BOOST_TYPEOF_short_STREAMS_BOOST_TYPEOF (short)
#define STREAMS_BOOST_TYPEOF_int_STREAMS_BOOST_TYPEOF (int)
#define STREAMS_BOOST_TYPEOF_long_STREAMS_BOOST_TYPEOF (long)
#define STREAMS_BOOST_TYPEOF_bool_STREAMS_BOOST_TYPEOF (bool)
#define STREAMS_BOOST_TYPEOF_unsigned_STREAMS_BOOST_TYPEOF (unsigned)
#define STREAMS_BOOST_TYPEOF_size_t_STREAMS_BOOST_TYPEOF (size_t)

#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_char          STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(char)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_short         STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(short)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_int           STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(int)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_long          STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(long)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_bool          STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(bool)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_unsigned      STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(unsigned)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_size_t        STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(size_t)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_unsignedchar  STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(unsigned char)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_unsignedshort STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(unsigned short)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_unsignedint   STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(unsigned int)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_unsignedlong  STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(unsigned long)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_signedchar    STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(signed char)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_signedshort   STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(signed short)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_signedint     STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(signed int)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_signedlong    STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(signed long)
#define STREAMS_BOOST_TYPEOF_MAKE_OBJ_integral(x)   STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(x)

#define STREAMS_BOOST_TYPEOF_INTEGRAL(X) integral(X) STREAMS_BOOST_TYPEOF_EAT
#define STREAMS_BOOST_TYPEOF_EAT_STREAMS_BOOST_TYPEOF
#define STREAMS_BOOST_TYPEOF_integral(X) (integral(X))

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM(Type)\
    (INTEGRAL_PARAM)\
    (Type)

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(Param)\
    STREAMS_BOOST_PP_SEQ_ELEM(1, Param)

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_EXPANDTYPE(Param)\
    STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(Param)

// INTEGRAL_PARAM "virtual functions" implementation

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_ENCODE(This, n)\
    typedef typename streams_boost::type_of::encode_integral<\
        STREAMS_BOOST_PP_CAT(V, n),\
        STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(This),\
        STREAMS_BOOST_PP_CAT(P, n)\
    >::type STREAMS_BOOST_PP_CAT(V, STREAMS_BOOST_PP_INC(n)); 

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_DECODE(This, n)\
    typedef streams_boost::type_of::decode_integral<STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(This), STREAMS_BOOST_PP_CAT(iter, n)> STREAMS_BOOST_PP_CAT(d, n);\
    static const STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(This) STREAMS_BOOST_PP_CAT(P, n) = STREAMS_BOOST_PP_CAT(d, n)::value;\
    typedef typename STREAMS_BOOST_PP_CAT(d, n)::iter STREAMS_BOOST_PP_CAT(iter, STREAMS_BOOST_PP_INC(n));

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_PLACEHOLDER(Param)\
    (STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(Param))0

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_DECLARATION_TYPE(Param)\
    STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_GETTYPE(Param)

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_PLACEHOLDER_TYPES(Param, n)\
    STREAMS_BOOST_PP_CAT(T,n)

#define STREAMS_BOOST_TYPEOF_INTEGRAL_PARAM_ISTEMPLATE 0

#endif//STREAMS_BOOST_TYPEOF_INTEGRAL_TEMPLATE_PARAM_HPP_INCLUDED
