// Copyright (C) 2004 Arkadiy Vertleyb
// Copyright (C) 2004 Peder Holt
// Use, modification and distribution is subject to the Boost Software
// License, Version 1.0. (http://www.streams_boost.org/LICENSE_1_0.txt)

#ifndef STREAMS_BOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED
#define STREAMS_BOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED

#include <streams_boost/typeof/typeof.hpp>

#include STREAMS_BOOST_TYPEOF_INCREMENT_REGISTRATION_GROUP()

STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned char)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned short)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned int)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned long)

STREAMS_BOOST_TYPEOF_REGISTER_TYPE(signed char)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(signed short)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(signed int)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(signed long)

STREAMS_BOOST_TYPEOF_REGISTER_TYPE(bool)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(char)

STREAMS_BOOST_TYPEOF_REGISTER_TYPE(float)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(double)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(long double)

#ifndef STREAMS_BOOST_NO_INTRINSIC_WCHAR_T
// If the following line fails to compile and you're using the Intel
// compiler, see http://lists.streams_boost.org/MailArchives/streams_boost-users/msg06567.php,
// and define STREAMS_BOOST_NO_INTRINSIC_WCHAR_T on the command line.
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(wchar_t)
#endif

#if (defined(STREAMS_BOOST_MSVC) && (STREAMS_BOOST_MSVC == 1200)) \
    || (defined(STREAMS_BOOST_INTEL_CXX_VERSION) && defined(_MSC_VER) && (STREAMS_BOOST_INTEL_CXX_VERSION <= 600)) \
    || (defined(__BORLANDC__) && (__BORLANDC__ == 0x600) && (_MSC_VER == 1200))
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned __int8)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(__int8)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned __int16)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(__int16)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned __int32)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(__int32)
#ifdef __BORLANDC__
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned __int64)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(__int64)
#endif
#endif

# if defined(STREAMS_BOOST_HAS_LONG_LONG)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(::streams_boost::ulong_long_type)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(::streams_boost::long_long_type)
#elif defined(STREAMS_BOOST_HAS_MS_INT64)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(unsigned __int64)
STREAMS_BOOST_TYPEOF_REGISTER_TYPE(__int64)
#endif

STREAMS_BOOST_TYPEOF_REGISTER_TYPE(void)

#endif//STREAMS_BOOST_TYPEOF_REGISTER_FUNDAMENTAL_HPP_INCLUDED
