// Boost.Signals library

// Copyright Douglas Gregor 2001-2003. Use, modification and
// distribution is subject to the Boost Software License, Version
// 1.0. (See accompanying file LICENSE_1_0.txt or copy at
// http://www.streams_boost.org/LICENSE_1_0.txt)

// For more information, see http://www.streams_boost.org

#ifndef STREAMS_BOOST_SIGNALS_SIGNAL0_HEADER
#define STREAMS_BOOST_SIGNALS_SIGNAL0_HEADER

#define STREAMS_BOOST_SIGNALS_NUM_ARGS 0
#define STREAMS_BOOST_SIGNALS_TEMPLATE_PARMS
#define STREAMS_BOOST_SIGNALS_TEMPLATE_ARGS
#define STREAMS_BOOST_SIGNALS_PARMS
#define STREAMS_BOOST_SIGNALS_ARGS
#define STREAMS_BOOST_SIGNALS_BOUND_ARGS
#define STREAMS_BOOST_SIGNALS_ARGS_AS_MEMBERS
#define STREAMS_BOOST_SIGNALS_COPY_PARMS
#define STREAMS_BOOST_SIGNALS_INIT_ARGS
#define STREAMS_BOOST_SIGNALS_ARG_TYPES

#include <streams_boost/signals/signal_template.hpp>

#undef STREAMS_BOOST_SIGNALS_ARG_TYPES
#undef STREAMS_BOOST_SIGNALS_INIT_ARGS
#undef STREAMS_BOOST_SIGNALS_COPY_PARMS
#undef STREAMS_BOOST_SIGNALS_ARGS_AS_MEMBERS
#undef STREAMS_BOOST_SIGNALS_BOUND_ARGS
#undef STREAMS_BOOST_SIGNALS_ARGS
#undef STREAMS_BOOST_SIGNALS_PARMS
#undef STREAMS_BOOST_SIGNALS_TEMPLATE_ARGS
#undef STREAMS_BOOST_SIGNALS_TEMPLATE_PARMS
#undef STREAMS_BOOST_SIGNALS_NUM_ARGS

#endif // STREAMS_BOOST_SIGNALS_SIGNAL0_HEADER
