# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.streams_boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.streams_boost.org for most recent version. */
#
# if !defined(STREAMS_BOOST_PP_LOCAL_LIMITS)
#    error STREAMS_BOOST_PP_ERROR:  local iteration boundaries are not defined
# elif !defined(STREAMS_BOOST_PP_LOCAL_MACRO)
#    error STREAMS_BOOST_PP_ERROR:  local iteration target macro is not defined
# else
#    if ~STREAMS_BOOST_PP_CONFIG_FLAGS() & STREAMS_BOOST_PP_CONFIG_EDG()
#        define STREAMS_BOOST_PP_LOCAL_S STREAMS_BOOST_PP_TUPLE_ELEM(2, 0, STREAMS_BOOST_PP_LOCAL_LIMITS)
#        define STREAMS_BOOST_PP_LOCAL_F STREAMS_BOOST_PP_TUPLE_ELEM(2, 1, STREAMS_BOOST_PP_LOCAL_LIMITS)
#    else
#        define STREAMS_BOOST_PP_VALUE STREAMS_BOOST_PP_TUPLE_ELEM(2, 0, STREAMS_BOOST_PP_LOCAL_LIMITS)
#        include <streams_boost/preprocessor/iteration/detail/start.hpp>
#        define STREAMS_BOOST_PP_VALUE STREAMS_BOOST_PP_TUPLE_ELEM(2, 1, STREAMS_BOOST_PP_LOCAL_LIMITS)
#        include <streams_boost/preprocessor/iteration/detail/finish.hpp>
#        define STREAMS_BOOST_PP_LOCAL_S STREAMS_BOOST_PP_LOCAL_SE()
#        define STREAMS_BOOST_PP_LOCAL_F STREAMS_BOOST_PP_LOCAL_FE()
#    endif
# endif
#
# if (STREAMS_BOOST_PP_LOCAL_S) > (STREAMS_BOOST_PP_LOCAL_F)
#    include <streams_boost/preprocessor/iteration/detail/rlocal.hpp>
# else
#    if STREAMS_BOOST_PP_LOCAL_C(0)
        STREAMS_BOOST_PP_LOCAL_MACRO(0)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(1)
        STREAMS_BOOST_PP_LOCAL_MACRO(1)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(2)
        STREAMS_BOOST_PP_LOCAL_MACRO(2)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(3)
        STREAMS_BOOST_PP_LOCAL_MACRO(3)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(4)
        STREAMS_BOOST_PP_LOCAL_MACRO(4)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(5)
        STREAMS_BOOST_PP_LOCAL_MACRO(5)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(6)
        STREAMS_BOOST_PP_LOCAL_MACRO(6)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(7)
        STREAMS_BOOST_PP_LOCAL_MACRO(7)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(8)
        STREAMS_BOOST_PP_LOCAL_MACRO(8)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(9)
        STREAMS_BOOST_PP_LOCAL_MACRO(9)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(10)
        STREAMS_BOOST_PP_LOCAL_MACRO(10)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(11)
        STREAMS_BOOST_PP_LOCAL_MACRO(11)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(12)
        STREAMS_BOOST_PP_LOCAL_MACRO(12)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(13)
        STREAMS_BOOST_PP_LOCAL_MACRO(13)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(14)
        STREAMS_BOOST_PP_LOCAL_MACRO(14)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(15)
        STREAMS_BOOST_PP_LOCAL_MACRO(15)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(16)
        STREAMS_BOOST_PP_LOCAL_MACRO(16)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(17)
        STREAMS_BOOST_PP_LOCAL_MACRO(17)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(18)
        STREAMS_BOOST_PP_LOCAL_MACRO(18)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(19)
        STREAMS_BOOST_PP_LOCAL_MACRO(19)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(20)
        STREAMS_BOOST_PP_LOCAL_MACRO(20)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(21)
        STREAMS_BOOST_PP_LOCAL_MACRO(21)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(22)
        STREAMS_BOOST_PP_LOCAL_MACRO(22)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(23)
        STREAMS_BOOST_PP_LOCAL_MACRO(23)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(24)
        STREAMS_BOOST_PP_LOCAL_MACRO(24)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(25)
        STREAMS_BOOST_PP_LOCAL_MACRO(25)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(26)
        STREAMS_BOOST_PP_LOCAL_MACRO(26)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(27)
        STREAMS_BOOST_PP_LOCAL_MACRO(27)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(28)
        STREAMS_BOOST_PP_LOCAL_MACRO(28)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(29)
        STREAMS_BOOST_PP_LOCAL_MACRO(29)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(30)
        STREAMS_BOOST_PP_LOCAL_MACRO(30)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(31)
        STREAMS_BOOST_PP_LOCAL_MACRO(31)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(32)
        STREAMS_BOOST_PP_LOCAL_MACRO(32)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(33)
        STREAMS_BOOST_PP_LOCAL_MACRO(33)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(34)
        STREAMS_BOOST_PP_LOCAL_MACRO(34)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(35)
        STREAMS_BOOST_PP_LOCAL_MACRO(35)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(36)
        STREAMS_BOOST_PP_LOCAL_MACRO(36)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(37)
        STREAMS_BOOST_PP_LOCAL_MACRO(37)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(38)
        STREAMS_BOOST_PP_LOCAL_MACRO(38)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(39)
        STREAMS_BOOST_PP_LOCAL_MACRO(39)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(40)
        STREAMS_BOOST_PP_LOCAL_MACRO(40)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(41)
        STREAMS_BOOST_PP_LOCAL_MACRO(41)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(42)
        STREAMS_BOOST_PP_LOCAL_MACRO(42)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(43)
        STREAMS_BOOST_PP_LOCAL_MACRO(43)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(44)
        STREAMS_BOOST_PP_LOCAL_MACRO(44)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(45)
        STREAMS_BOOST_PP_LOCAL_MACRO(45)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(46)
        STREAMS_BOOST_PP_LOCAL_MACRO(46)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(47)
        STREAMS_BOOST_PP_LOCAL_MACRO(47)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(48)
        STREAMS_BOOST_PP_LOCAL_MACRO(48)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(49)
        STREAMS_BOOST_PP_LOCAL_MACRO(49)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(50)
        STREAMS_BOOST_PP_LOCAL_MACRO(50)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(51)
        STREAMS_BOOST_PP_LOCAL_MACRO(51)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(52)
        STREAMS_BOOST_PP_LOCAL_MACRO(52)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(53)
        STREAMS_BOOST_PP_LOCAL_MACRO(53)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(54)
        STREAMS_BOOST_PP_LOCAL_MACRO(54)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(55)
        STREAMS_BOOST_PP_LOCAL_MACRO(55)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(56)
        STREAMS_BOOST_PP_LOCAL_MACRO(56)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(57)
        STREAMS_BOOST_PP_LOCAL_MACRO(57)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(58)
        STREAMS_BOOST_PP_LOCAL_MACRO(58)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(59)
        STREAMS_BOOST_PP_LOCAL_MACRO(59)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(60)
        STREAMS_BOOST_PP_LOCAL_MACRO(60)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(61)
        STREAMS_BOOST_PP_LOCAL_MACRO(61)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(62)
        STREAMS_BOOST_PP_LOCAL_MACRO(62)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(63)
        STREAMS_BOOST_PP_LOCAL_MACRO(63)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(64)
        STREAMS_BOOST_PP_LOCAL_MACRO(64)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(65)
        STREAMS_BOOST_PP_LOCAL_MACRO(65)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(66)
        STREAMS_BOOST_PP_LOCAL_MACRO(66)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(67)
        STREAMS_BOOST_PP_LOCAL_MACRO(67)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(68)
        STREAMS_BOOST_PP_LOCAL_MACRO(68)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(69)
        STREAMS_BOOST_PP_LOCAL_MACRO(69)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(70)
        STREAMS_BOOST_PP_LOCAL_MACRO(70)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(71)
        STREAMS_BOOST_PP_LOCAL_MACRO(71)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(72)
        STREAMS_BOOST_PP_LOCAL_MACRO(72)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(73)
        STREAMS_BOOST_PP_LOCAL_MACRO(73)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(74)
        STREAMS_BOOST_PP_LOCAL_MACRO(74)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(75)
        STREAMS_BOOST_PP_LOCAL_MACRO(75)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(76)
        STREAMS_BOOST_PP_LOCAL_MACRO(76)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(77)
        STREAMS_BOOST_PP_LOCAL_MACRO(77)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(78)
        STREAMS_BOOST_PP_LOCAL_MACRO(78)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(79)
        STREAMS_BOOST_PP_LOCAL_MACRO(79)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(80)
        STREAMS_BOOST_PP_LOCAL_MACRO(80)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(81)
        STREAMS_BOOST_PP_LOCAL_MACRO(81)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(82)
        STREAMS_BOOST_PP_LOCAL_MACRO(82)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(83)
        STREAMS_BOOST_PP_LOCAL_MACRO(83)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(84)
        STREAMS_BOOST_PP_LOCAL_MACRO(84)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(85)
        STREAMS_BOOST_PP_LOCAL_MACRO(85)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(86)
        STREAMS_BOOST_PP_LOCAL_MACRO(86)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(87)
        STREAMS_BOOST_PP_LOCAL_MACRO(87)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(88)
        STREAMS_BOOST_PP_LOCAL_MACRO(88)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(89)
        STREAMS_BOOST_PP_LOCAL_MACRO(89)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(90)
        STREAMS_BOOST_PP_LOCAL_MACRO(90)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(91)
        STREAMS_BOOST_PP_LOCAL_MACRO(91)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(92)
        STREAMS_BOOST_PP_LOCAL_MACRO(92)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(93)
        STREAMS_BOOST_PP_LOCAL_MACRO(93)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(94)
        STREAMS_BOOST_PP_LOCAL_MACRO(94)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(95)
        STREAMS_BOOST_PP_LOCAL_MACRO(95)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(96)
        STREAMS_BOOST_PP_LOCAL_MACRO(96)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(97)
        STREAMS_BOOST_PP_LOCAL_MACRO(97)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(98)
        STREAMS_BOOST_PP_LOCAL_MACRO(98)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(99)
        STREAMS_BOOST_PP_LOCAL_MACRO(99)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(100)
        STREAMS_BOOST_PP_LOCAL_MACRO(100)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(101)
        STREAMS_BOOST_PP_LOCAL_MACRO(101)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(102)
        STREAMS_BOOST_PP_LOCAL_MACRO(102)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(103)
        STREAMS_BOOST_PP_LOCAL_MACRO(103)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(104)
        STREAMS_BOOST_PP_LOCAL_MACRO(104)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(105)
        STREAMS_BOOST_PP_LOCAL_MACRO(105)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(106)
        STREAMS_BOOST_PP_LOCAL_MACRO(106)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(107)
        STREAMS_BOOST_PP_LOCAL_MACRO(107)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(108)
        STREAMS_BOOST_PP_LOCAL_MACRO(108)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(109)
        STREAMS_BOOST_PP_LOCAL_MACRO(109)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(110)
        STREAMS_BOOST_PP_LOCAL_MACRO(110)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(111)
        STREAMS_BOOST_PP_LOCAL_MACRO(111)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(112)
        STREAMS_BOOST_PP_LOCAL_MACRO(112)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(113)
        STREAMS_BOOST_PP_LOCAL_MACRO(113)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(114)
        STREAMS_BOOST_PP_LOCAL_MACRO(114)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(115)
        STREAMS_BOOST_PP_LOCAL_MACRO(115)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(116)
        STREAMS_BOOST_PP_LOCAL_MACRO(116)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(117)
        STREAMS_BOOST_PP_LOCAL_MACRO(117)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(118)
        STREAMS_BOOST_PP_LOCAL_MACRO(118)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(119)
        STREAMS_BOOST_PP_LOCAL_MACRO(119)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(120)
        STREAMS_BOOST_PP_LOCAL_MACRO(120)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(121)
        STREAMS_BOOST_PP_LOCAL_MACRO(121)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(122)
        STREAMS_BOOST_PP_LOCAL_MACRO(122)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(123)
        STREAMS_BOOST_PP_LOCAL_MACRO(123)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(124)
        STREAMS_BOOST_PP_LOCAL_MACRO(124)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(125)
        STREAMS_BOOST_PP_LOCAL_MACRO(125)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(126)
        STREAMS_BOOST_PP_LOCAL_MACRO(126)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(127)
        STREAMS_BOOST_PP_LOCAL_MACRO(127)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(128)
        STREAMS_BOOST_PP_LOCAL_MACRO(128)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(129)
        STREAMS_BOOST_PP_LOCAL_MACRO(129)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(130)
        STREAMS_BOOST_PP_LOCAL_MACRO(130)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(131)
        STREAMS_BOOST_PP_LOCAL_MACRO(131)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(132)
        STREAMS_BOOST_PP_LOCAL_MACRO(132)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(133)
        STREAMS_BOOST_PP_LOCAL_MACRO(133)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(134)
        STREAMS_BOOST_PP_LOCAL_MACRO(134)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(135)
        STREAMS_BOOST_PP_LOCAL_MACRO(135)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(136)
        STREAMS_BOOST_PP_LOCAL_MACRO(136)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(137)
        STREAMS_BOOST_PP_LOCAL_MACRO(137)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(138)
        STREAMS_BOOST_PP_LOCAL_MACRO(138)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(139)
        STREAMS_BOOST_PP_LOCAL_MACRO(139)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(140)
        STREAMS_BOOST_PP_LOCAL_MACRO(140)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(141)
        STREAMS_BOOST_PP_LOCAL_MACRO(141)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(142)
        STREAMS_BOOST_PP_LOCAL_MACRO(142)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(143)
        STREAMS_BOOST_PP_LOCAL_MACRO(143)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(144)
        STREAMS_BOOST_PP_LOCAL_MACRO(144)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(145)
        STREAMS_BOOST_PP_LOCAL_MACRO(145)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(146)
        STREAMS_BOOST_PP_LOCAL_MACRO(146)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(147)
        STREAMS_BOOST_PP_LOCAL_MACRO(147)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(148)
        STREAMS_BOOST_PP_LOCAL_MACRO(148)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(149)
        STREAMS_BOOST_PP_LOCAL_MACRO(149)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(150)
        STREAMS_BOOST_PP_LOCAL_MACRO(150)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(151)
        STREAMS_BOOST_PP_LOCAL_MACRO(151)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(152)
        STREAMS_BOOST_PP_LOCAL_MACRO(152)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(153)
        STREAMS_BOOST_PP_LOCAL_MACRO(153)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(154)
        STREAMS_BOOST_PP_LOCAL_MACRO(154)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(155)
        STREAMS_BOOST_PP_LOCAL_MACRO(155)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(156)
        STREAMS_BOOST_PP_LOCAL_MACRO(156)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(157)
        STREAMS_BOOST_PP_LOCAL_MACRO(157)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(158)
        STREAMS_BOOST_PP_LOCAL_MACRO(158)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(159)
        STREAMS_BOOST_PP_LOCAL_MACRO(159)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(160)
        STREAMS_BOOST_PP_LOCAL_MACRO(160)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(161)
        STREAMS_BOOST_PP_LOCAL_MACRO(161)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(162)
        STREAMS_BOOST_PP_LOCAL_MACRO(162)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(163)
        STREAMS_BOOST_PP_LOCAL_MACRO(163)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(164)
        STREAMS_BOOST_PP_LOCAL_MACRO(164)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(165)
        STREAMS_BOOST_PP_LOCAL_MACRO(165)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(166)
        STREAMS_BOOST_PP_LOCAL_MACRO(166)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(167)
        STREAMS_BOOST_PP_LOCAL_MACRO(167)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(168)
        STREAMS_BOOST_PP_LOCAL_MACRO(168)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(169)
        STREAMS_BOOST_PP_LOCAL_MACRO(169)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(170)
        STREAMS_BOOST_PP_LOCAL_MACRO(170)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(171)
        STREAMS_BOOST_PP_LOCAL_MACRO(171)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(172)
        STREAMS_BOOST_PP_LOCAL_MACRO(172)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(173)
        STREAMS_BOOST_PP_LOCAL_MACRO(173)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(174)
        STREAMS_BOOST_PP_LOCAL_MACRO(174)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(175)
        STREAMS_BOOST_PP_LOCAL_MACRO(175)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(176)
        STREAMS_BOOST_PP_LOCAL_MACRO(176)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(177)
        STREAMS_BOOST_PP_LOCAL_MACRO(177)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(178)
        STREAMS_BOOST_PP_LOCAL_MACRO(178)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(179)
        STREAMS_BOOST_PP_LOCAL_MACRO(179)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(180)
        STREAMS_BOOST_PP_LOCAL_MACRO(180)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(181)
        STREAMS_BOOST_PP_LOCAL_MACRO(181)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(182)
        STREAMS_BOOST_PP_LOCAL_MACRO(182)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(183)
        STREAMS_BOOST_PP_LOCAL_MACRO(183)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(184)
        STREAMS_BOOST_PP_LOCAL_MACRO(184)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(185)
        STREAMS_BOOST_PP_LOCAL_MACRO(185)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(186)
        STREAMS_BOOST_PP_LOCAL_MACRO(186)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(187)
        STREAMS_BOOST_PP_LOCAL_MACRO(187)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(188)
        STREAMS_BOOST_PP_LOCAL_MACRO(188)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(189)
        STREAMS_BOOST_PP_LOCAL_MACRO(189)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(190)
        STREAMS_BOOST_PP_LOCAL_MACRO(190)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(191)
        STREAMS_BOOST_PP_LOCAL_MACRO(191)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(192)
        STREAMS_BOOST_PP_LOCAL_MACRO(192)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(193)
        STREAMS_BOOST_PP_LOCAL_MACRO(193)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(194)
        STREAMS_BOOST_PP_LOCAL_MACRO(194)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(195)
        STREAMS_BOOST_PP_LOCAL_MACRO(195)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(196)
        STREAMS_BOOST_PP_LOCAL_MACRO(196)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(197)
        STREAMS_BOOST_PP_LOCAL_MACRO(197)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(198)
        STREAMS_BOOST_PP_LOCAL_MACRO(198)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(199)
        STREAMS_BOOST_PP_LOCAL_MACRO(199)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(200)
        STREAMS_BOOST_PP_LOCAL_MACRO(200)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(201)
        STREAMS_BOOST_PP_LOCAL_MACRO(201)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(202)
        STREAMS_BOOST_PP_LOCAL_MACRO(202)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(203)
        STREAMS_BOOST_PP_LOCAL_MACRO(203)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(204)
        STREAMS_BOOST_PP_LOCAL_MACRO(204)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(205)
        STREAMS_BOOST_PP_LOCAL_MACRO(205)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(206)
        STREAMS_BOOST_PP_LOCAL_MACRO(206)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(207)
        STREAMS_BOOST_PP_LOCAL_MACRO(207)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(208)
        STREAMS_BOOST_PP_LOCAL_MACRO(208)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(209)
        STREAMS_BOOST_PP_LOCAL_MACRO(209)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(210)
        STREAMS_BOOST_PP_LOCAL_MACRO(210)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(211)
        STREAMS_BOOST_PP_LOCAL_MACRO(211)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(212)
        STREAMS_BOOST_PP_LOCAL_MACRO(212)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(213)
        STREAMS_BOOST_PP_LOCAL_MACRO(213)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(214)
        STREAMS_BOOST_PP_LOCAL_MACRO(214)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(215)
        STREAMS_BOOST_PP_LOCAL_MACRO(215)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(216)
        STREAMS_BOOST_PP_LOCAL_MACRO(216)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(217)
        STREAMS_BOOST_PP_LOCAL_MACRO(217)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(218)
        STREAMS_BOOST_PP_LOCAL_MACRO(218)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(219)
        STREAMS_BOOST_PP_LOCAL_MACRO(219)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(220)
        STREAMS_BOOST_PP_LOCAL_MACRO(220)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(221)
        STREAMS_BOOST_PP_LOCAL_MACRO(221)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(222)
        STREAMS_BOOST_PP_LOCAL_MACRO(222)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(223)
        STREAMS_BOOST_PP_LOCAL_MACRO(223)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(224)
        STREAMS_BOOST_PP_LOCAL_MACRO(224)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(225)
        STREAMS_BOOST_PP_LOCAL_MACRO(225)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(226)
        STREAMS_BOOST_PP_LOCAL_MACRO(226)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(227)
        STREAMS_BOOST_PP_LOCAL_MACRO(227)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(228)
        STREAMS_BOOST_PP_LOCAL_MACRO(228)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(229)
        STREAMS_BOOST_PP_LOCAL_MACRO(229)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(230)
        STREAMS_BOOST_PP_LOCAL_MACRO(230)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(231)
        STREAMS_BOOST_PP_LOCAL_MACRO(231)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(232)
        STREAMS_BOOST_PP_LOCAL_MACRO(232)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(233)
        STREAMS_BOOST_PP_LOCAL_MACRO(233)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(234)
        STREAMS_BOOST_PP_LOCAL_MACRO(234)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(235)
        STREAMS_BOOST_PP_LOCAL_MACRO(235)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(236)
        STREAMS_BOOST_PP_LOCAL_MACRO(236)
#    endif

#    if STREAMS_BOOST_PP_LOCAL_C(237)
        STREAMS_BOOST_PP_LOCAL_MACRO(237)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(238)
        STREAMS_BOOST_PP_LOCAL_MACRO(238)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(239)
        STREAMS_BOOST_PP_LOCAL_MACRO(239)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(240)
        STREAMS_BOOST_PP_LOCAL_MACRO(240)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(241)
        STREAMS_BOOST_PP_LOCAL_MACRO(241)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(242)
        STREAMS_BOOST_PP_LOCAL_MACRO(242)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(243)
        STREAMS_BOOST_PP_LOCAL_MACRO(243)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(244)
        STREAMS_BOOST_PP_LOCAL_MACRO(244)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(245)
        STREAMS_BOOST_PP_LOCAL_MACRO(245)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(246)
        STREAMS_BOOST_PP_LOCAL_MACRO(246)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(247)
        STREAMS_BOOST_PP_LOCAL_MACRO(247)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(248)
        STREAMS_BOOST_PP_LOCAL_MACRO(248)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(249)
        STREAMS_BOOST_PP_LOCAL_MACRO(249)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(250)
        STREAMS_BOOST_PP_LOCAL_MACRO(250)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(251)
        STREAMS_BOOST_PP_LOCAL_MACRO(251)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(252)
        STREAMS_BOOST_PP_LOCAL_MACRO(252)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(253)
        STREAMS_BOOST_PP_LOCAL_MACRO(253)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(254)
        STREAMS_BOOST_PP_LOCAL_MACRO(254)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(255)
        STREAMS_BOOST_PP_LOCAL_MACRO(255)
#    endif
#    if STREAMS_BOOST_PP_LOCAL_C(256)
        STREAMS_BOOST_PP_LOCAL_MACRO(256)
#    endif
# endif
#
# undef STREAMS_BOOST_PP_LOCAL_LIMITS
#
# undef STREAMS_BOOST_PP_LOCAL_S
# undef STREAMS_BOOST_PP_LOCAL_F
#
# undef STREAMS_BOOST_PP_LOCAL_MACRO
