# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.streams_boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.streams_boost.org for most recent version. */
#
# include <streams_boost/preprocessor/slot/detail/shared.hpp>
#
# undef STREAMS_BOOST_PP_LOCAL_SE
#
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_4
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_5
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_6
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_7
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_8
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_9
# undef STREAMS_BOOST_PP_LOCAL_SE_DIGIT_10
#
# if STREAMS_BOOST_PP_SLOT_TEMP_3 == 0
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 0
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 1
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 1
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 2
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 2
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 3
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 3
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 4
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 4
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 5
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 5
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 6
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 6
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 7
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 7
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 8
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 8
# elif STREAMS_BOOST_PP_SLOT_TEMP_3 == 9
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3 9
# endif
#
# if STREAMS_BOOST_PP_SLOT_TEMP_2 == 0
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 0
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 1
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 1
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 2
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 2
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 3
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 3
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 4
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 4
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 5
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 5
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 6
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 6
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 7
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 7
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 8
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 8
# elif STREAMS_BOOST_PP_SLOT_TEMP_2 == 9
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2 9
# endif
#
# if STREAMS_BOOST_PP_SLOT_TEMP_1 == 0
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 0
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 1
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 1
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 2
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 2
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 3
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 3
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 4
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 4
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 5
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 5
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 6
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 6
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 7
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 7
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 8
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 8
# elif STREAMS_BOOST_PP_SLOT_TEMP_1 == 9
#    define STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1 9
# endif
#
# if STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3
#    define STREAMS_BOOST_PP_LOCAL_SE() STREAMS_BOOST_PP_SLOT_CC_3(STREAMS_BOOST_PP_LOCAL_SE_DIGIT_3, STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2, STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1)
# elif STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2
#    define STREAMS_BOOST_PP_LOCAL_SE() STREAMS_BOOST_PP_SLOT_CC_2(STREAMS_BOOST_PP_LOCAL_SE_DIGIT_2, STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1)
# else
#    define STREAMS_BOOST_PP_LOCAL_SE() STREAMS_BOOST_PP_LOCAL_SE_DIGIT_1
# endif
