/* Copyright 2006-2008 Joaquin M Lopez Munoz.
 * Distributed under the Boost Software License, Version 1.0.
 * (See accompanying file LICENSE_1_0.txt or copy at
 * http://www.streams_boost.org/LICENSE_1_0.txt)
 *
 * See http://www.streams_boost.org/libs/flyweight for library home page.
 */

/* no include guards */

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=1
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1 \
template<typename T0> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(1)\
template<typename T0> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(1)
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=2
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_2 \
template<typename T0,typename T1> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(2)\
template<typename T0,typename T1> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(2)\
template<typename T0,typename T1> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(2)\
template<typename T0,typename T1> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(2)
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=3
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_3 \
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)\
template<typename T0,typename T1,typename T2> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(3)
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=4
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_4 \
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2,T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)\
template<typename T0,typename T1,typename T2,typename T3> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2,const T3& t3)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(4)
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=5
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_5 \
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,T1& t1,const T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(T0& t0,const T1& t1,const T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,T1& t1,const T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2,T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2,T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2,const T3& t3,T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)\
template<typename T0,typename T1,typename T2,typename T3,typename T4> STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME(const T0& t0,const T1& t1,const T2& t2,const T3& t3,const T4& t4)STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY(5)
#endif

#if   STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS==0
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS
#elif STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS==1
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1
#elif STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS==2
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_2
#elif STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS==3
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_2                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_3
#elif STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS==4
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_2                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_3                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_4
#else /* STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS==5 */
#define STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_2                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_3                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_4                \
STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_5
#endif

/* generate the overloads */

STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS

/* clean up */

#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_OVERLOADS

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=1
#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_1
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=2
#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_2
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=3
#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_3
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=4
#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_4
#endif

#if STREAMS_BOOST_FLYWEIGHT_LIMIT_PERFECT_FWD_ARGS>=5
#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWDS_5
#endif

/* user supplied argument macros */

#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_NAME
#undef STREAMS_BOOST_FLYWEIGHT_PERFECT_FWD_BODY
